name: Playwright E2E Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_WIX_CLIENT_ID: ${{ secrets.NEXT_PUBLIC_WIX_CLIENT_ID }}
      WIX_COLLECTION_TEAM: ${{ secrets.WIX_COLLECTION_TEAM }}
      WIX_COLLECTION_BOARD_MEMBERS: ${{ secrets.WIX_COLLECTION_BOARD_MEMBERS }}
      WIX_COLLECTION_MEMBERS: ${{ secrets.WIX_COLLECTION_MEMBERS }}
      WIX_COLLECTION_CULTURE_RESOURCES: ${{ secrets.WIX_COLLECTION_CULTURE_RESOURCES }}
      WIX_COLLECTION_BUSINESS_RESOURCES: ${{ secrets.WIX_COLLECTION_BUSINESS_RESOURCES }}
      WIX_COLLECTION_BENEFITS: ${{ secrets.WIX_COLLECTION_BENEFITS }}
      WIX_COLLECTION_TESTIMONIALS: ${{ secrets.WIX_COLLECTION_TESTIMONIALS }}
      WIX_COLLECTION_CTA: ${{ secrets.WIX_COLLECTION_CTA }}
      WIX_COLLECTION_CALENDAR: ${{ secrets.WIX_COLLECTION_CALENDAR }}
      WIX_COLLECTION_HOME: ${{ secrets.WIX_COLLECTION_HOME }}
      RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
      RESEND_TARGET_EMAIL: ${{ secrets.RESEND_TARGET_EMAIL }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Make prouction build
        run: npm run build
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
